version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  embedding-service:
    build:
      context: ./embedding-service
    container_name: embedding-service
    ports:
      - "5001:5000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: content-manager-ai-agent
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_URL=http://embedding-service:5000
      - OLLAMA_URL=http://host.docker.internal:11434
      - COLLECTION_NAME=content_memory
    depends_on:
      - qdrant
      - embedding-service
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: content-manager-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  qdrant_storage:
